package com.vitorthemyth.blessedroullet.presenter.tracker.use_cases

data class TrackerUseCases(
    val checkTicTacStrategy: CheckTicTacStrategy,
    val checkFerrariStrategy: CheckFerrariStrategy,
    val checkEvenOddStrategy: CheckEvenOddStrategy,
    val checkOneByOneStrategy: CheckOneByOneStrategy,
    val checkExtremeStrategy: CheckExtremeStrategy,
    val checkMirrorStrategy: CheckMirrorStrategy,
    val checkArcherStrategy: CheckArcherStrategy,
    val checkBugattiStrategy: CheckBugattiStrategy,
    val check30AndNeighbors: Check30AndNeighbors,
    val check17AndNeighbors: Check17AndNeighbors,
    val check22AndNeighbors: Check22AndNeighbors,
    val check21AndNeighbors: Check21AndNeighbors,
    val check20AndNeighbors: Check20AndNeighbors,
    val check3AndNeighbors: Check3AndNeighbors,
    val check13AndNeighbors: Check13AndNeighbors,
    val check26AndNeighbors: Check26AndNeighbors,
    val check14AndNeighbors: Check14AndNeighbors,
    val check27AndNeighbors: Check27AndNeighbors,
    val check24AndNeighbors: Check24AndNeighbors,
    val check23AndNeighbors: Check23AndNeighbors,
    val check33AndNeighbors: Check33AndNeighbors,
    val check16AndNeighbors: Check16AndNeighbors,
    val check9AndNeighbors: Check9AndNeighbors,
    val check19AndNeighbors: Check19AndNeighbors,
    val check5Combo: Check5Combo,
    val check35Combo: Check35Combo
)
